import os

DEFAULT_SUBSCRIPTION_ID = os.getenv('DEFAULT_SUBSCRIPTION_ID', 1)
DEFAULT_TRIAL_DAYS = os.getenv('DEFAULT_TRIAL_DAYS', 7)
DEFAULT_SUBSCRIPTION_DURATION = os.getenv('DEFAULT_SUBSCRIPTION_DURATION', 30)
DEFAULT_USER_ROLE_ID = os.getenv('DEFAULT_USER_ROLE_ID', 2)
ACTIVATION_MAIL_SUBJECT = os.getenv('ACTIVATION_MAIL_SUBJECT')
USER_CREATION_MAIL_SUBJECT = os.getenv('USER_CREATION_MAIL_SUBJECT')